[package]
name = "raytacing"
version = "0.1.0"
authors = ["Dan <Daniel_Maycock@yahoo.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
rayon = "1.2.0" 

[profile.release]
debug = true